version: '3.4'

services:
  safqah.auth:
    image: ${DOCKER_REGISTRY-}safqahauth
    build:
      context: .
      dockerfile: services/Safqah.Auth/Dockerfile
    ports:
      - "44392:80"
    depends_on:
      - postgresql

  safqah.investors:
    image: ${DOCKER_REGISTRY-}safqahinvestors
    build:
      context: .
      dockerfile: services/Safqah.Investor/Dockerfile
    ports:
      - "44393:80"
    depends_on:
      - postgresql

  safqah.opportunities:
    image: ${DOCKER_REGISTRY-}safqahopportunities
    build:
      context: .
      dockerfile: services/Safqah.Opportunities/Dockerfile
    ports:
      - "44394:80"
    depends_on:
      - postgresql
      - rabbitmq

  safqah.opportunities.consumer:
    image: ${DOCKER_REGISTRY-}safqahopportunitiesconsumer
    build:
      context: .
      dockerfile: Safqah.Opportunities.Consumer/Dockerfile
    depends_on:
      - rabbitmq
      - postgresql

  safqah.payment:
    image: ${DOCKER_REGISTRY-}safqahpayment
    build:
      context: .
      dockerfile: services/Safqah.Payment/Dockerfile
    ports:
      - "44395:80"
    depends_on:
      - postgresql
      - rabbitmq
    command: ["./wait-for-it.sh", "postgresql:5432", "--", "dotnet", "Safqah.Payment.dll"]

  safqah.wallet:
    image: ${DOCKER_REGISTRY-}safqahwallet
    build:
      context: .
      dockerfile: services/Safqah.Wallet/Dockerfile
    ports:
      - "44322:80"
      - "44391:80"
    depends_on:
      - postgresql

  safqah.wallet.consumer:
    image: ${DOCKER_REGISTRY-}safqahwalletconsumer
    build:
      context: .
      dockerfile: Safqah.Wallet.Consumer/Dockerfile
    depends_on:
      - rabbitmq
      - postgresql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Safqah
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
